import React from 'react'
import './globals.css'
import "../i18n"

export const metadata = {
  title: 'Lesson 5 ',
  description: 'Generated by create next app',
}

const Layout = ({ children }) => {
  return (
    <html>
      <body>
        <div>{children}</div>
      </body>
    </html>
  )
}

export default Layout
