import Header from '@/components/Header/Header'
import React from 'react'
import './globals.css'

export const metadata = {
  title: 'Lesson 5 ',
  description: 'Generated by create next app',
}

const Layout = ({children}) => {
  return (
    <html>
      <body>        
        <div>
          
          {children}  
        </div>
      </body>
    </html>
  )
}

export default Layout
